workspace: &workspace
  ~/repo

# Cache
cache_paths: &cache_paths
  paths:
    - ~/repo/.gradle
    - ~/.gradle
    - ~/.m2
cache_key: &cache_key
   gradle-dependencies-{{ checksum "build.gradle.kts" }}
restore_cache: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      # fallback to using the latest cache if no exact match is found
      - gradle-dependencies-
save_cache: &save_cache
  save_cache:
    <<: *cache_paths
    key: *cache_key

# Workspace
attach_build_workspace: &attach_build_workspace
  attach_workspace:
    at: *workspace
persist_build_workspace: &persist_build_workspace
  persist_to_workspace:
    root: *workspace
    paths:
      - build/*

version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: *workspace
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  build:
    executor: java-executor
    steps:
      - checkout
      - *restore_cache
      - run: gradle dependencies
      - run: gradle build
      - *save_cache
      - *persist_build_workspace

  test:
    executor: java-executor
    steps:
      - checkout
      - *restore_cache
      - *attach_build_workspace
      - run: gradle test
      - store_test_results:
          path: build/test-results

  verify-java:
    executor: java-executor
    steps:
      - checkout
      - *restore_cache
      - *attach_build_workspace
      - run: javac -version
      - run:
          command: |
            cd src/test/resources/org/larl/printer/JavaPrinterTest
            mv  expectedModule.txt Test.java
            javac Test.java

  verify-kotlin:
    executor: java-executor
    steps:
      - checkout
      - *restore_cache
      - restore_cache:
          keys:
            - kotlin-install
      - *attach_build_workspace
      - run:
          command: |
            curl -s https://get.sdkman.io | bash
            source ~/.sdkman/bin/sdkman-init.sh
            sdk install kotlin
            kotlinc -version
      - save_cache:
          paths:
            - ~/.sdkman
          key: kotlin-install
      - run:
          command: |
            source ~/.sdkman/bin/sdkman-init.sh
            cd src/test/resources/org/larl/printer/KotlinPrinterTest
            mv  expectedModule.txt Test.kt
            kotlinc Test.kt

  verify-javascript:
    docker:
      - image: circleci/node
    working_directory: *workspace
    steps:
      - checkout
      - *restore_cache
      - *attach_build_workspace
      - run: node --version
      - run:
          command: |
            cd src/test/resources/org/larl/printer/JavaScriptPrinterTest
            mv  expectedModule.txt Test.mjs
            node --experimental-modules Test.mjs

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - verify-java
      - verify-kotlin
      - verify-javascript
