workspace: &workspace
  ~/repo

# Cache
cache_paths: &cache_paths
  paths:
    - ~/repo/.gradle
    - ~/.gradle
    - ~/.m2
cache_key: &cache_key
   v1-dependencies-{{ checksum "build.gradle.kts" }}
restore_cache: &restore_cache
  restore_cache:
    keys:
      - *cache_key
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-
save_cache: &save_cache
  save_cache:
    <<: *cache_paths
    key: *cache_key

# Workspace
attach_build_workspace: &attach_build_workspace
  attach_workspace:
    at: *workspace
persist_build_workspace: &persist_build_workspace
  persist_to_workspace:
    root: *workspace
    paths:
      - build/*

version: 2.1

executors:
  gradle-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: *workspace
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  build:
    executor: gradle-executor
    steps:
      - checkout
      - *restore_cache
      - run: gradle dependencies
      - run: gradle build
      - *save_cache
      - *persist_build_workspace

  test:
    executor: gradle-executor
    steps:
      - checkout
      - *restore_cache
      - *attach_build_workspace
      - run: gradle test
      - store_test_results:
          path: build/test-results

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
